### ISSUE TITLE
Deprecated code

### ISSUE THREAD

**Issue by hratoanina** [0xPolygonZero/plonky2#1031]
In `recursive_verifier.rs`, the struct `RecursiveAllProof` is a recursive version of an `AllProof`, which contains all non-SNARKed original STARK proofs. However it seems that, in the current proving flow, individual STARKs are SNARKed and recursively shortened before being bundled together. Is `RecursiveAllProof` completely deprecated?

It seems there are also other components that are deprecated / unused within the evm crate, is there any plan to remove them in the future? It can get confusing.

**Comment by Nashtare** [comment]
Dealt with in https://github.com/0xPolygonZero/plonky2/pull/1281.
