### ISSUE TITLE
hello, In the test contract example, how do you get the output of calling the contract?

### ISSUE THREAD

**Issue by itpika** [0xPolygonZero/plonky2#1042]
evm/tests/test_basic_smart_contract.rs

**Comment by qyzxcswbll** [comment]
I have the same question

**Comment by Nashtare** [comment]
The zkEVM's goal is to prove Ethereum state transitions. As such, it only cares about an input and output states, some additional metadata, and will prove that the transition is valid (i.e. respects the Ethereum specs).
Integration tests here have either been generated through a py-evm script or taken from the Ethereum official test suite, but the zkEVM isn't outputting contract calls.
