### ISSUE TITLE
No out of gas check in `sys_stop`

### ISSUE THREAD

**Issue by hratoanina** [0xPolygonZero/plonky2#1106]
https://github.com/mir-protocol/plonky2/blob/3de92d9ed1721cec133e4e1e1b3ec7facb756ccf/evm/src/cpu/kernel/asm/core/terminate.asm#L4

The `sys_stop` function does not check if the current gas usage exceeds the context gas limit. This can happen since simple opcodes which are directly evaluated in the CPU Stark update the gas usage, but do not check that it stays below the limit. This makes, for example, some of the `gasMeasure` tests of the EVM test suite fail.
To enforce the check, adding the line `%charge_gas_const(0)` does the trick, but the issue might be more widespread and I find the hotfix pretty ugly. Do you have any suggestions?

On a related note, this might enable a minor DOS attack: a very long code with only simple opcodes which would trigger an OOG error very early would be evaluated in its entirety by the EVM, making the CPU trace very long for no reason.

**Comment by Nashtare** [comment]
Alternatively to make the check slightly prettier, we could just have a new macro for current gas check:
```
%macro check_gas
    // stack: kexit_info
    %ctx_gas_limit
    // stack: gas_limit, kexit_info
    DUP2 %shr_const(192)
    // stack: gas_used, gas_limit, kexit_info
    GT
    // stack: out_of_gas, kexit_info
    %jumpi(fault_exception)
    // stack: kexit_info
%endmacro
```
