### ISSUE TITLE
Reduce the size of the memory table

### ISSUE THREAD

**Issue by nbgl** [0xPolygonZero/plonky2#1120]
Few ideas:
1. Native instruction for reading 32 bytes (in separate memory locations) into one register. This will require a separate table, but this table is needed to sanely do PUSH anyway.
2. Native instruction for _writing_ 32 bytes (again, in separate memory locations) from one register. This is very similar to 1. but will require range checks to show that the register was broken up correctly.
3. Keep the top of the stack in the CPU table registers.

Another idea, but I'm not sure how realistic it is, would be to only have one read row per instruction. We do not write to the code segment (? or at least it's frozen once we do write to it), so we don't have to worry about it changing. But I'm not sure how to do multiplicity in the CTL.

**Comment by Nashtare** [comment]
@nbgl Now that I have spent some time on the byte packing approach, I am not sure this will yield a significant enough improvement to justify the new table. 
Available implementation is there if it matters: [plonky2/packing_table](https://github.com/topos-protocol/plonky2/tree/packing_table).

Let's consider a typical example of a full `mload_packing` call, reading 32 bytes. We currently do:

```asm
  - 31 ADD (3 memory rows each)
  -  3 DUP3 (2 memory rows each)
  - 93 DUP4 (2 memory rows each)
  - 31 DUP5 (2 memory rows each)
  - 32 MLOAD_GENERAL (5 memory rows each)
  - 31 %add_const (4 memory rows each)
  - 31 %eq_const (4 memory rows each)
  - 31 %shl_const (4 memory rows each)
  -  1 %stack which corresponds to 2 SWAP and 4 POP (4 and 1 memory rows each)
  -  4 POP (1 memory row each)
  - 31 JUMPI (2 memory rows)

→ total = 957 memory rows
```

With the `BytePackingStark` table, we can reduce it to:

```asm
  - 1 MLOAD_32BYTES (5 + 32 memory rows)
  - 1 SWAP (4 memory rows)
  - 1 JUMP (1 memory row)

→ total 42 memory rows
```

For a global reduction of 915 memory rows for a full `mload_packing` call. However, many places only read a single byte, removing only 19 rows. For portions actually using a full `mload_packing`, like the curve precompiles, the gain is negligible compared to the overhead induced by the rest of the operations. Below are a few trace sizes obtained from specific tests from the EVM suite:

-  `pairingTest_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 369696 | N/A | 1465022 | 561 | 54 |  4999 | 6916972 | 
| BP | 367278 |  75 | 1452768 |  557 | 54 |  4979 | 6907820 | 


-  `ecmul_0-0_0_21000_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 47388 | N/A | 353217 | 634 | 127 |  5374 | 1654468 | 
| BP | 46551 |  255 | 345916 |  630 | 127 |  5354 | 1650110 | 


-  `ecadd_0-0_0-0_21000_0_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 47506 | N/A | 353774 | 634 | 127 |  5383 | 1654939 | 
| BP | 46576 |  256 | 346031 |  630 | 127 |  5363 | 1650271 | 


-  `CallSha256_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 23564 | N/A | 168848 | 543 | 42 |  6039 | 883714 | 
| BP | 20498 |  357 | 149784 |  539 | 42 |  6019 | 871661 | 


-  `CALLCODEBlake2f_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 14779 | N/A | 114401 | 541 | 40 |  3789 | 509411 | 
| BP | 14779 |  36 | 113808 |  537 | 40 |  3769 | 508377 | 


If we wanted to continue down that road, we could further try to reduce CPU/Memory lengths by also dealing with LE packing/unpacking. For instance `mload_packing_u64_LE` instructions amount for (ignoring the macro call overhead) 177 memory rows, which could get down to 18 (a 159 rows reduction), which for blake2f would mean a 4.1k memory accesses reduction. A similar approach could be down for unpacking macros.

**Comment by Nashtare** [comment]
Actually the `MSTORE_32BYTES` operation for byte unpacking has much more impact than I had expected! 

Below are some results for the same tests as above. In  $\textsf{\color{red}red}$ are the lengths that will pad to a smaller power-of-two than the main branch version.


-  `pairingTest_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 369696 | N/A | 1465022 | 561 | 54 |  4999 | 6916972 | 
| B P/uP | 362403 |  216 | 1419558 |  556 | 54 |  4974 | 6887215 | 


-  `ecmul_0-0_0_21000_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 47388 | N/A | 353217 | 634 | 127 |  5374 | 1654468 | 
| B P/uP | 30126 |  827 | $\textsf{\color{red}233551}$ |  629 | 127 |  5349 | $\textsf{\color{red}926926}$ | 


-  `ecadd_0-0_0-0_21000_0_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 47506 | N/A | 353774 | 634 | 127 |  5383 | 1654939 | 
| B P/uP | 30151 |  828 | $\textsf{\color{red}233666}$ |  629 | 127 |  5358 | $\textsf{\color{red}927086}$ | 


-  `CallSha256_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 23564 | N/A | 168848 | 543 | 42 |  6039 | 883714 | 
| B P/uP | 16283 |  522 | $\textsf{\color{red}120854}$ |  538 | 42 |  6014 | 526828 | 


-  `CALLCODEBlake2f_0`

| Branch | Arith |BP | CPU |Keccak | KeccakSp |Logic | Memory |
|--------|--------|--------|--------|--------|--------|--------|--------|
| Main | 14779 | N/A | 114401 | 541 | 40 |  3789 | 509411 | 
| B P/uP| 11698 |  130 | 92793 |  536 | 40 |  3764 | 495416 | 

I'll cleanup a bit and open a PR.

**Comment by Nashtare** [comment]
All 3 suggestions have been integrated to `main` :)
