### ISSUE TITLE
Profile and optimize kernel code

### ISSUE THREAD

**Issue by nbgl** [0xPolygonZero/plonky2#1121]
The aim is to reduce the number of CPU table rows.

**Comment by pgebheim** [comment]
Closing as we wait for more specific tasks to schedule into a future milestone.

**Comment by Nashtare** [comment]
PRs #1301, #1302, #1303, #1304 and #1305 are all related to Kernel optimization, though in general profiling depends on which scenario we place ourselves (small txns / precompile calls / contract creation / ...) so not sure a single profiling approach is doable in general.
