### ISSUE TITLE
Add table for initial and final MPT hashing

### ISSUE THREAD

**Issue by wborgeaud** [0xPolygonZero/plonky2#1175]
The MPT logic in `hash_initial_tries` and `hash_final_tries` is quite costly at the moment. For example, in the proof of block 17582017, `hash_initial_tries` and `hash_final_tries` both use approximately 6M CPU rows and 19.5M memory rows. 
For comparison, this [UniswapV2 swap](https://etherscan.io/tx/0x2aafd9640e07d429ce7b1510825c961e9e133ea54b4e2545118871a4371c86af) uses 4.2M CPU rows and 13M memory rows.

Adding separate tables for the initial and final MPT hashing would therefore significantly reduce the size of the CPU and memory tables.

**Comment by Nashtare** [comment]
Depending on the timeline for the code freeze, I don't think this will be fully ready + have time for a proper review to be included.

**Comment by Nashtare** [comment]
Side note on heavy operations, we have a branch for amortizing `mem_cpy` by 40%, we haven't opened a PR yet for it (waiting on #1291).

**Comment by Nashtare** [comment]
Should we still consider this issue? Given that we're focusing on continuations, soon we'll be able to proceed block payloads in one go, removing all the intermediary MPTs loading and hashing (i.e. loading the entire state when starting, and hashing it at the end), effectively reducing the need for such table, if not removing it completely.

**Comment by wborgeaud** [comment]
Agreed, this is obsolete with continuations.
