### ISSUE TITLE
Panic handling

### ISSUE THREAD

**Issue by Nashtare** [0xPolygonZero/plonky2#1247]
There are several places where the prover can currently panic on invalid inputs, either through `unwrap()` / `expect()` or specific methods like `U256::as_u32()` which implicitely perform an unwrapping.

Ideally we'd like to have all those removed by returning an `Error` instead, though this will imply some important refactoring in several pieces of the evm crate. Is there any preferred approach for tackling this? 

@npwardberkeley: for context, I've been trying to remove also the unchecked calls to `U256::as_usize()` which are not part of #1231 that you reviewed, which made me realize that some modules like the `prover_input` one are filled with panic risks.

**Comment by dvdplm** [comment]
I would suggest adopting a hard but simple rule on panics: not allowed outside tests. A total ban on `unwrap()`s. All `expect()` calls should carry a full explanation as to why the panic will never happen. Example:

```rust
let a = Some(true);
// moar code
let b = a.expect("Initialized as Some above and never touched after; qed");
```

Code processing user input and/or data off the network should never assume the data is valid.

**Comment by Nashtare** [comment]
Handled by #1231 and #1250
