### ISSUE TITLE
How to generate an Ethereum friendly plonk verifier?

### ISSUE THREAD

**Issue by martyall** [0xPolygonZero/plonky2#1374]
I can't seem to find this information anywhere, so I'm gonna try asking here. I have a [toy language](https://github.com/martyall/calc) and I'm looking for a plonk backend. Among the options I've seen for rust implementations, this seems very mature. I am curious though if there is any way to generate a solidity verifying contract for a given circuit, or if anyone has a toolchain for serializing circuits to a format which would be friendly for something like snarkjs? To be concrete, how would you go about creating a verifer for something like [factorial](https://github.com/0xPolygonZero/plonky2/blob/main/plonky2/examples/factorial.rs) on Ethereum?

**Comment by pgebheim** [comment]
Using https://github.com/succinctlabs/gnark-plonky2-verifier/ you can verify the STARK generated by plonky2 and generate plonk proof that can be verified on Ethereum.

We will have a full end to end of this working for plonky2 proofs soon.

I'm gonna close this issue and [direct you to the Discord](https://discord.gg/Fqt2BD5a) for more discussion on the topic

**Comment by 0xbok** [comment]
Hi @pgebheim, do you know of a way to directly verify plonky2 STARK proof in EVM?

**Comment by xiyu1984** [comment]
> That's not tractable since the resulting proofs are large. The method should be to verify it within snark, and verify that on chain.
> 
> You can use gnark to do this: https://github.com/succinctlabs/gnark-plonky2-verifier

Hey @pgebheim ,

Do you have some details about this issue?

https://github.com/succinctlabs/gnark-plonky2-verifier/issues/46

Now I'm also trying to rewrite `Serialize` for `HashOut`, and I found that there are some slight differences in the `common_circuit_data.json` between the files generated by `plonky2` and the input of `gnark-plonky2-verifier`.
