### ISSUE TITLE
Starky proof failing to verify recursively 

### ISSUE THREAD

**Issue by armanthepythonguy** [0xPolygonZero/plonky2#1631]
I am trying to verify a starky proof inside a plonky2 circuit. I have followed the same procedure as per the FibonacciStark.rs file, but I am getting error :- 

I have my custom Starky proof, which can be successfully proved and verified with prove and verify functions but fails during recursive verification.

thread 'dense::tests::test_stark_recursive' panicked at src/dense.rs:115:70:
called `Result::unwrap()` on an `Err` value: Partition containing Wire(Wire { row: 53, column: 40 }) was set twice with different values: 5380601374886916272 != 11172169064086565555
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test dense::tests::test_stark_recursive ... FAILED

**Comment by armanthepythonguy** [comment]
Here's some code snippets :- 
```
fn recursive_verifier(stark: DenseStark, proof: StarkProofWithPublicInputs<F,C,D>, inner_config: &StarkConfig) -> Result<()>{

        let circuit_config = CircuitConfig::standard_recursion_config();
        let mut builder = CircuitBuilder::<F, D>::new(circuit_config);

        let mut pw: PartialWitness<F> = PartialWitness::new();
        let degree_bits = proof.proof.recover_degree_bits(inner_config);

        println!("{:?}", degree_bits);

        let pt = add_virtual_stark_proof_with_pis(&mut builder, &stark, inner_config, degree_bits, 0, 0);
        set_stark_proof_with_pis_target(&mut pw, &pt, &proof, builder.zero())?;

        verify_stark_proof_circuit::<F, C, DenseStark, D>(&mut builder, stark, pt, inner_config);
        
        let data = builder.build::<C>();
        let proof = data.prove(pw)?;
        data.verify(proof)
    }
```
Also
```
let trace = stark.generate_trace(pub_inputs.to_vec());
        println!(
            "Duration to generate trace :- {}",
            start.elapsed().as_millis()
        );

        start = Instant::now();
        let (proof, layer_sign) = stark.prove(pub_inputs.to_vec(), trace, *inputs.last().unwrap());
        println!(
            "Duration to generate proof :- {}",
            start.elapsed().as_millis()
        );
        recursive_verifier(stark, proof, &StarkConfig::standard_fast_config())
```

**Comment by Nashtare** [comment]
Hello,
can we have access to the code that generated this error, along with the version of plonky2 / starky you used and the command you used? Thank you.

**Comment by armanthepythonguy** [comment]
Here you can find all the relevant codes, also let me know if you want more details, I will add you as a collaborator to the repo.
https://gist.github.com/armanthepythonguy/2e5a7240f82c3fec4207ab6aa1fbd71f

**Comment by armanthepythonguy** [comment]
Also, I would want to learn more about the constraint degree function used while defining the starky circuits. I have seen many examples where we have used values either 2 or 3, Can you please guide me into the relevance of the constraint degree and if any docs you can share

**Comment by armanthepythonguy** [comment]
Any updates @Nashtare

**Comment by Nashtare** [comment]
You have commented out some constraints on the recursive side. Hence you are having discrepancies between native and recursive constraints (they must be identical, otherwise a recursive verifier circuit is verifying a _different_ statement than the native verifier).

**Comment by armanthepythonguy** [comment]
@Nashtare Can you please check once, I have updated the code but this the error remains
https://gist.github.com/armanthepythonguy/f90fc45ec1d1c68bb3ac638064e7eb6b

**Comment by Nashtare** [comment]
Your second constraint has
`builder.sub_extension(tmp2, next_values[4])`

while it should be
`builder.sub_extension(next_values[4], tmp2)`

to match the native constraint.
