### ISSUE TITLE
low heap mode

### ISSUE THREAD

**Issue by Sladuca** [0xPolygonZero/plonky2#632]
There are many environments where heap usage comes at a significant premium (for me, a Solana program which has only 32KB of heap), and I think it would be good to reduce heap usage. It might also help reduce cache footprint for large-ish circuits.

There's a lot of instances in this library in which unnecessary `Vec`s are used where slices would suffice. Unfortunately, this might requires breaking interface changes.

To avoid breaking existing stuff, we can have a `low_heap` feature with alternative types and function signatures (e.g. returning iterators, taking mutable references to slices). Another option is to duplicate code and have a separate `lite_verifier` crate/module that re-implements just the stuff needed by the verifier.

Examples:
* [`to_fri_openings`](https://github.com/mir-protocol/plonky2/blob/60227b98288583012ff1c606c8464d4aee754c01/plonky2/src/plonk/proof.rs#L323) can return an iterator over the openings instead and save a pretty significant amount of heap memory
* [`Challenger`'s `input_buffer`](https://github.com/mir-protocol/plonky2/blob/60227b98288583012ff1c606c8464d4aee754c01/plonky2/src/iop/challenger.rs#L36) gets [quite large when observing FRI openings](https://github.com/mir-protocol/plonky2/blob/60227b98288583012ff1c606c8464d4aee754c01/plonky2/src/plonk/get_challenges.rs#L53), and we can set a maximum size absorb buffered inputs whenever it reaches that size
* [`eval_unfiltered`](https://github.com/mir-protocol/plonky2/blob/60227b98288583012ff1c606c8464d4aee754c01/plonky2/src/gates/gate.rs#L25) in `Gate` can take a `ConstraintConsumer` (or a new analogous thing) instead of allocating and returning a `Vec` every time.

I'm already working on this stuff because I need it, and I'm happy to open a PR. Just want to gague what approach is preferred and how OK we are with breaking interface changes here/there

**Comment by dlubarov** [comment]
Just to reiterate, I'd prefer if we can reduce memory use of the main verifier, to avoid splitting its code.

**Comment by dlubarov** [comment]
My understanding is the Solana verification effort has stopped for now, so this probably isn't needed
