### ISSUE TITLE
What do you think about adding `is_greater_than`, `is_less_than` to CircuitBuilder

### ISSUE THREAD

**Issue by MizukiSonoko** [0xPolygonZero/plonky2#877]
Hello.

I'm developing ZK + VC(Verifiable Credential) now and studying ZK. so, I started using Plonky2 because I wondered if it would be possible to create a function that would satisfy the W3C specifications https://www.w3.org/TR/vc-data-model/#personally-identifiable-information .
> issuing ageOver [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) instead of date of birth [verifiable credentials](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) when a [verifier](https://www.w3.org/TR/vc-data-model/#dfn-verifier) wants to determine if an [entity](https://www.w3.org/TR/vc-data-model/#dfn-entities) is over the age of 18.

Currently, `CircuitBuilder` only supports `is_equal`, but What do you think about adding `is_greater_than`, `is_less_than`.
so I wrote implements. ( I know it's not enough, should update like this https://github.com/mir-protocol/plonky2/commit/ad1aa4ae10d775fddf7c5a9b1345b417103f8417 )
https://github.com/MizukiSonoko/plonky2/commit/683814f428a86c66fd6dde97d55268f2a7540e48

Example codes.
https://github.com/MizukiSonoko/plonky2/commit/347bb6ee3d59c58fabe2d3cf76111b62dee44b1f

I don't know much about zk / plonky2 yet....
so there may be a better way or I could be saying something wrong. My apologies.

regards

**Comment by dlubarov** [comment]
Hi, I think those gadgets appear to be under-constrained. I.e. in `is_greater_than`, it seems a malicious prover could set `greater_than` to 1 without violating constraints. Your generator sets the right values, but in Plonky2 generators are just code that an honest prover runs, they don't prevent dishonest provers from setting other values.

Comparisons are a bit tricky in circuits. I think the simplest approach that works for arbitrary field elements is to split the two elements into their canonical bit representations, then do a binary comparison.

**Comment by MizukiSonoko** [comment]
Thanks for the reply!!

Yes, it is indeed less constrains.
I'm trying to implement more constraints. https://github.com/mir-protocol/plonky2/commit/f72cf2faf110311145ef1595112d6d0d98349936 (Still doesn't work, but I'll try )

Regards.

**Comment by dlubarov** [comment]
I think this may not be widely useful enough to add to the core of Plonky2, so closing for now.
