### ISSUE TITLE
How to achieve the ~43kB proof size claimed in the white paper?

### ISSUE THREAD

**Issue by EazyReal** [0xPolygonZero/plonky2#916]
Hi, 
I tried to modify the `FriConfig` to achieve the ~43kB proof size claimed in the white paper `plonky2.pdf`.
However, the resulting proof size is ~63kB for a circuit (dummy proof provided in the example) with a 2^12 degree.
Am I missing anything that can further optimize the proof size? 
Thanks! 

More specifically, this is what I changed  in `plonky2/src/plonk/circuit_data.rs`:

```rust
  pub fn size_opt_recursion_config() -> Self {
      Self {
          num_wires: 135,
          num_routed_wires: 80,
          num_constants: 2,
          use_base_arithmetic_gate: true,
          security_bits: 100,
          num_challenges: 2,
          zero_knowledge: false,
          max_quotient_degree_factor: 8,
          fri_config: FriConfig {
              rate_bits: 8,           //plonk2.pdf ch. 8
              cap_height: 5,          // ?
              proof_of_work_bits: 16, // 3*28+16 = 100 => 8*11+12
              reduction_strategy: FriReductionStrategy::MinSize(Some(3)),
              num_query_rounds: 11, // 3*28+16 = 100 => 8*11+12
          },
      }
  }
```

**Comment by dlubarov** [comment]
Hi, we can improve it a bit further with a chain of a few recursive proofs, each one smaller than the previous one. That way the final proof will be for a somewhat smaller circuit. We have a `test_size_optimized_recursion` to demonstrate this.
